name: manim-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - manim
  - jupyterlab
  - ffmpeg
  - tectonic            # ✅ Lightweight LaTeX engine
  - pygments
  - pip
  - pip:
      - manim[jupyter]  # ✅ Enables %%manim magic
