name: manim-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - manim
  - jupyterlab
  - ffmpeg
  - texlive-core        # ✅ full LaTeX (reliable)
  - pygments
  - pip
  - pip:
      - manim[jupyter]
