name: manim-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - manim
  - jupyterlab
  - ffmpeg
  - texlive-core       # ✅ FIX: full LaTeX compiler for MathTex
  - pygments
  - pip
  - pip:
      - manim[jupyter]
