name: manim-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - manim
  - jupyterlab
  - ffmpeg
  - tectonic        # lightweight LaTeX
  - pygments
  - pip
  - pip:
      - manim[jupyter]  # enables %%manim IPython extension
