# -*- coding: utf-8 -*-
"""golden_ratio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QdFPR-vXcmoBG5yemf3mLltW00E5bQq
"""

from manim import *

class GoldenRatioVisualization(Scene):
    def construct(self):
        title = Text("The Golden Ratio (𝜙 ≈ 1.618)", font_size=48, color=YELLOW)
        title.to_edge(UP, buff=0.5)
        self.play(Write(title))
        self.wait(1)

        A = Dot(LEFT * 3)
        B = Dot(RIGHT * 3)
        AB = Line(A.get_center(), B.get_center())
        label_A = Text("A", font_size=24).next_to(A, DOWN)
        label_B = Text("B", font_size=24).next_to(B, DOWN)
        self.play(Create(AB), FadeIn(A), FadeIn(B), Write(label_A), Write(label_B))
        self.wait(1)

        golden_ratio = 1.618
        total_length = 6
        long_part = total_length / (1 + 1 / golden_ratio)
        C_pos = A.get_center() + RIGHT * long_part
        C = Dot(C_pos, color=BLUE)
        label_C = Text("C", font_size=24).next_to(C, DOWN)
        AC = Line(A.get_center(), C_pos, color=BLUE)
        CB = Line(C_pos, B.get_center(), color=GREEN)
        self.play(Create(AC), FadeIn(C), Write(label_C))
        self.wait(1)
        self.play(Create(CB))
        self.wait(1)

        ratio1 = MathTex(r"\frac{AB}{AC} \approx 1.618", font_size=36)
        ratio2 = MathTex(r"\frac{AC}{CB} \approx 1.618", font_size=36)
        ratio1.next_to(AB, UP, buff=0.5)
        ratio2.next_to(ratio1, DOWN, buff=0.25)
        self.play(Write(ratio1))
        self.wait(1)
        self.play(Write(ratio2))
        self.wait(2)

        golden_rect = Rectangle(width=golden_ratio * 2, height=2, color=ORANGE)
        golden_rect.shift(DOWN * 2)
        golden_text = Text("Golden Rectangle", font_size=24).next_to(golden_rect, DOWN)
        self.play(Create(golden_rect), Write(golden_text))
        self.wait(3)

        self.play(*[FadeOut(mob) for mob in self.mobjects])